#!/bin/bash

server=CpTwoServer

if [ $# -ne 0 ]; then
    if [ "${1,,}" = "rsa" ]; then
        server=CpOneServer
    elif [ "${1,,}" != "aes" ]; then
        echo Usage: $0 [aes rsa]
        exit 1
    fi
fi

cd resources
java -cp ../build/classes/main/ $server
